# General Site Configuration
site_name: STMP26
site_url: https://matas-noreika.github.io/BIP26Dublin-personal
site_description: Additional information for Dublin STMP
site_author: Matas Noreika
repo_name: matas-noreika/BIP26Dublin-personal
repo_url: https://github.com/matas-noreika/BIP26Dublin-personal

# Plugin configuration
plugins:
  - blog # enables blog on site

# Navigation Setup
nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - Setup:
    - ArduinoIDE: arduino-ide.md
    - Git-Basics: git-basics.md
  - Sensors:
    - BMP280:
      - AI-Overview: sensors/bmp280-ai-overview.md
    - QMI8658C:
      - AI-Overview: sensors/qmi8658c-ai-overview.md
    LC29H:
      - AI-Overview: lc29h-ai-overview.md

# Site display Configuration
theme:
  name: material # Required if using mkdocs-material
  # logo: img/icon.png # icon to use in site
  # favicon: img/favicon.png # site favicon
  language: en # language presetting for browser SEO
  # Color definitions
  palette:
    scheme: slate # Dark mode, default - light mode
    primary: indigo
    accent: indigo
  # Font configuration
  font:
    text: Roboto
    code: Roboto Mono
  # Additional features
  features:
    - navigation.footer # enables customisation of footer
    - content.code.copy # enable copy code button on code blocks
    - content.code.select # enable line selection mode
    - content.code.annotate # enables code annotation

# Footer customisation
extra:
  # Disable the auto made with mkdocs-material message
  generator: false
  # Add custom copyright notice
  copyright: Copyright &copy; 2026 Matas Noreika
  # Social link Configuration
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/matas-noreika
      name: matas-noreika
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/matas.noreika
      name: matas.noreika

